# -*- coding: utf-8 -*-
"""ros_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v3EHwL5ysqzSjdRAdUyAwyQfvywOV3w4
"""

import rospy
from std_srvs.srv import Empty

def main():
    rospy.init_node('main')
    
    rospy.wait_for_service('/go_to_kitchen')
    go_to_kitchen = rospy.ServiceProxy('/go_to_kitchen', Empty)
    response = go_to_kitchen()

    
    rospy.wait_for_service('/stop')
    stop = rospy.ServiceProxy('/stop', Empty)
    response = stop()

    
    rospy.wait_for_service('/go_home')
    go_home = rospy.ServiceProxy('/go_home', Empty)
    response = go_home()

    
    rospy.wait_for_service('/stop')
    stop = rospy.ServiceProxy('/stop', Empty,)
    response = stop()

    
if __name__ == '__main__':
    main()