# -*- coding: utf-8 -*-
"""ros_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v3EHwL5ysqzSjdRAdUyAwyQfvywOV3w4
"""

import rospy
from std_srvs.srv import Empty, EmptyResponse
import time

def go_home(request1):
    rospy.loginfo("Going to home.")
    rospy.sleep(2) 
    rospy.loginfo("Arrived")
    return EmptyResponse()

def go_to_kitchen(request2):
    rospy.loginfo("Going to kitchen.")
    rospy.sleep(2) 
    rospy.loginfo("Arrived")
    return EmptyResponse()

def stop(request3):
    rospy.loginfo("Stop!.")
    return EmptyResponse()

go_home = rospy.Service('/go_home', Empty, go_home)

go_to_kitchen = rospy.Service('/go_to_kitchen', Empty, go_to_kitchen)

stop = rospy.Service('/stop', Empty, stop)